services:
  # Un servizio web che espone le API
  - type: web
    name: nba-stats-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nba-stats-db
          property: connectionString
      - key: ADMIN_PASSWORD
        sync: false  # Impostare manualmente nell'interfaccia di Render
      - key: PYTHON_VERSION
        value: 3.10.7

databases:
  # Database PostgreSQL per memorizzare le chiavi
  - name: nba-stats-db
    plan: free  # Cambiare in base alle necessità 